name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v4
    - name: Run script
      run: python hello.py

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create an artifact of repository
      uses: actions/upload-artifact@v2
      with:
        name: source
