name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script
      run: python hello.py

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create an artifact of repository
      uses: actions/upload-artifact@v4
      with:
        name: hello
        path: .
